# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:

  # Docker image configurations

  ios_config: &ios_config
    working_directory: ~/repo
    macos:
      xcode: "10.1.0"

  # Export environment variables
  export_previous_release_version: &export_previous_release_version
    run:
      name: Export previous version number to environment variable
      command: echo "export PREVIOUS_SDK_VERSION=`cat Outbrain.m | grep "OB_SDK_VERSION" | cut -d "=" -f2 | cut -d \" -f2`" >> $BASH_ENV
      working_directory: SDK-sources/OutbrainSDK/

  export_release_version: &export_release_version
    run:
      name: Export new version number to environment variable
      command: echo "export RELEASE_VERSION=$(cut -d '/' -f2 <<< $CIRCLE_BRANCH)" >> $BASH_ENV

jobs:
  ios_default:
    <<: *ios_config
    steps:
      - checkout

      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: OutbrainSDK
          working_directory: SDK-sources

  # ios_release:
  #    <<: *ios_config
  #   steps:
  #     - checkout
  #
  #     - run:
  #         name: Clean previous OutbrainSDK.framework
  #         command: |
  #           if [ -d OutbrainSDK.framework ]; then
  #             rm -fr OutbrainSDK.framework
  #           fi
  #         working_directory: Samples/OutbrainDemo
  #
  #     - run:
  #         name: Cleaing the SDK project - OBFramework
  #         command: xcodebuild clean -target OBFramework
  #         working_directory: SDK-sources
  #
  #     - run:
  #         name: Cleaing the SDK project - OutbrainSDK
  #         command: xcodebuild clean -target OutbrainSDK
  #         working_directory: SDK-sources
  #
  #     - run:
  #         name: Building the SDK project
  #         command: xcodebuild -target OBFramework
  #         working_directory: SDK-sources

workflows:
  version: 2
  workflow:
    jobs:
      - ios_default
