platform :ios do
    before_all do
      setup_circle_ci
    end
end

lane :certificates do
    match(type: "development", readonly: true)
end    

lane :sdk_tests do
    run_tests(
        project: "SwiftSDK-sources/OutbrainSDK.xcodeproj", 
        scheme: "OutbrainSDK", 
        devices: ["iPhone 14 Pro Max"])
end

lane :sfwebview_prod do
    gym(
	project: "Samples/OutbrainDemo/OutbrainDemo.xcodeproj",
	scheme: "SFWebView-Prod",
        configuration: "Release",     
        destination: "generic/platform=iOS",
        export_method: "enterprise",
        export_options: {
            provisioningProfiles: {
                "com.outbrain.SFWebView-Prod": "match InHouse com.outbrain.SFWebView-Prod"
            },
            certificates: ["iPhone Distribution: OUTBRAIN INCORPORATED"]
        })
end