platform :ios do
    before_all do
      setup_circle_ci
    end
end

lane :certificates do
    match(type: "development", readonly: true)
end    

lane :build_sfwebview do
    match(type: "development", readonly: true)
    gym(
        project: "Samples/OutbrainDemo/OutbrainDemo.xcodeproj",
        scheme: "SFWebView-Prod",
        configuration: "Release",     
        destination: "generic/platform=iOS",
        export_method: "enterprise",
        export_options: {
            provisioningProfiles: {
                "com.outbrain.SFWebView-Prod": "match InHouse com.outbrain.SFWebView-Prod"
            }
        })
end