# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OutbrainDemoSwift' do
    pod 'Alamofire', '~> 4.8.1'
    pod 'AlamofireImage', '~> 3.5'
end

target 'OutbrainDemoSwiftTests' do

end

target 'OutbrainDemoSwiftUITests' do

end

