name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Building the SDK project
        working-directory: ./SDK-sources
        run: |
          xcodebuild -target OBFramework -UseModernBuildSystem=NO
          # xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
      
      - name: Build Sample Apps - Journal
        working-directory: ./Samples/OutbrainDemo
        run: |
          xcodebuild -project OutbrainDemo.xcodeproj -scheme Journal -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro' build

      - name: Build Sample Apps - SmartFeed
        working-directory: ./Samples/OutbrainDemo
        run: |
          xcodebuild -project OutbrainDemo.xcodeproj -scheme SmartFeed -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro' build

      - name: Run SDK tests
        working-directory: ./SDK-sources
        run: |
          xcodebuild test-without-building -project OutbrainSDK.xcodeproj -scheme OutbrainSDK -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro' 
